server:
  port: 8888

spring:  profiles:    active: native  cloud:    config:      server:        git:
          uri: https://github.com/igor-ferreira-almeida/microservice-repo.git          search-paths: fornecedor